name: C Memory and Data Structures CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run Unit Tests
        run: ./build/c_memory_and_data_structures
